title: Sabiq Muhtadi
#logo: /assets/img/headshot_circle.png
#description: text below image

theme: jekyll-theme-minimal

# Contact Information
email: smuhtadi@unc.edu
google_scholar_link: https://scholar.google.com/citations?user=GOGKF0QAAAAJ&hl=en

